### ISSUE TITLE
Modifica PopUp Ordine - Inserimento campo resto

### ISSUE THREAD

**Issue by Bcrusade** [Bcrusade/Gestionale-Popolare-Pyton#1]
Nel pop-up di riepilogo Ordine deve essere inserito un campo in cui inserire il valore di contanti dati dall’ordinante per il calcolo in automatico del resto da dare

**Comment by Bcrusade** [comment]
Ho inserito la funzione:  

Attualmente non funzione, lascio a voi perché non capisco come mai non viene trovata

//Calcolo resto
    function calcolaSottrazione() {
      var num1 = parseFloat(document.getElementById("num1").value);

      var risultatoElement = document.getElementById("risultato");

      if (isNaN(num1) || isNaN(GrandTotal)) {
        risultatoElement.textContent =
          "Inserisci un numero valido e assicurati che il numero esterno sia definito.";
        return;
      }

      if (num1 < GrandTotal) {
        alert(
          "C'è un errore sul pagamento. Il numero inserito è inferiore al totale."
        );
        return;
      }

      var risultato = Math.abs(GrandTotal - num1);

      risultatoElement.textContent =
        "Resto: " + risultato.toFixed(2) + " €";
    }

    function handleKeyPress(event) {
      if (event.keyCode === 13) {
        calcolaSottrazione();
      }
    }

**Comment by Silmat** [comment]
La funzione resto dovrebbe essere visualizzata solo se flaggato Contanti; se il flag è su POS non dovrebbe essere visibile.

Verificare anche l'impaginazione della riga con il resto

**Comment by Bcrusade** [comment]
Ciao Matteo, il campo è già visibile solo se si preme il tasto cliente, ora correggo l'impaginazione
